swagger: '2.0'
info:
  title: Mail App API
  version: "1.0.0"
# the domain of the service
host: localhost:8083
# array of all schemes that your API supports
schemes:
  - http
  - https
produces:
  - application/json
paths:
  /users/search:
    get:
      summary: An api to search user by name
      tags:
        - User
      parameters:
        - name: q
          in: query
          description: search token
          required: true
          type: string
      responses:
        200:
          description: An array of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /dealers:
    get:
      summary: Get all dealers
      tags:
        - Dealer
      responses:
        200:
          description: An array of dealers
          schema:
            type: array
            items:
              $ref: '#/definitions/Dealer'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /parcels:
    post:
      summary: Create a new parcel entry
      produces:
        - application/json
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - Parcel
      parameters:
        - name: parcel
          in: body
          description: Dealer of parcel
          required: true
          schema:
            $ref: '#/definitions/ParcelCreate'
      responses:
        200:
          description: Parcel Created.
          schema: 
            type: string
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /parcels/open:
    get:
      summary: Get all parcels with status open
      tags:
        - Parcel
      responses:
        200:
          description: Array of all parcels with status open 
          schema:
            type: array
            items:
              $ref: '#/definitions/Parcel'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /parcels/closed:
    get:
      summary: Get all parcels with status closed.
      tags:
        - Parcel
      responses:
        200:
          description: Array of all parcels with status closed.
          schema:
            type: array
            items:
              $ref: '#/definitions/Parcel'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  User:
    type: object
    required: ["emp_id","email"]
    properties:
      id:
        type: string
      emp_id:
        type: string
      name:
        type: string
      email:
        type: string
        format: email
        description: User's personal/official email address
      phone_no:
        type: string
        description: User's personal/official phone number
  Dealer:
    type: object
    required: ["name"]
    properties:
      id:
        type: string
      name:
        type: string
      icon:
        type: string
        format: uri
  Parcel:
    type: object
    properties:
      id:
        type: string
      dealer:
        $ref: '#/definitions/Dealer'
      owner:
        $ref: '#/definitions/User'
      reciever:
        $ref: '#/definitions/User'
      status:
        type: boolean
      recieved_date:
        type: string
      pickup_date:
        type: string
  ParcelCreate:
    type: object
    required: ["dealerId", "ownerId"]
    properties:
      dealerId:
        type: string
      ownerId:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
