package models

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Dealer dealer

swagger:model Dealer
*/
type Dealer struct {

	/* icon
	 */
	Icon *strfmt.URI `db:"icon" json:"icon,omitempty"`

	/* id
	 */
	ID *string `db:"id" json:"id,omitempty"`

	/* name
	 */
	Name *string `db:"name" json:"name,omitempty"`
}

// Validate validates this dealer
func (m *Dealer) Validate(formats strfmt.Registry) error {
	return nil
}
