package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*Dealer dealer

swagger:model Dealer
*/
type Dealer struct {

	/* dealer icon
	 */
	DealerIcon *strfmt.URI `json:"dealer_icon,omitempty"`

	/* dealer id
	 */
	DealerID *string `json:"dealer_id,omitempty"`

	/* dealer name

	Required: true
	*/
	DealerName string `json:"dealer_name"`
}

// Validate validates this dealer
func (m *Dealer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDealerName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Dealer) validateDealerName(formats strfmt.Registry) error {

	if err := validate.RequiredString("dealer_name", "body", string(m.DealerName)); err != nil {
		return err
	}

	return nil
}
